export const P = Object.freeze({
  DASHBOARD_READ: 'dashboard:read',
  LOAN_QUEUE_READ: 'loan_queue:read',
  LOAN_QUEUE_WRITE: 'loan_queue:write',
  LOAN_QUEUE_REVIEW: 'loan_queue:review',
  MEMBERSHIPS_READ: 'memberships:read',
  MEMBERSHIPS_WRITE: 'memberships:write',
  MEMBERSHIPS_REVIEW: 'memberships:review',
  MEMBERSHIPS_UPDATE: 'memberships:update',
  MEMBERSHIPS_BLACKLIST: 'memberships:blacklist',
  LOAN_APPLICATIONS_READ: 'loan_applications:read',
  LOAN_APPLICATIONS_WRITE: 'loan_applications:write',
  LOAN_APPLICATIONS_UPDATE: 'loan_applications:update',
  LOAN_APPLICATIONS_REVIEW: 'loan_applications:review',
  LOANS_READ: 'loans:read',
  LOANS_UPDATE: 'loans:update',
  LOANS_DISBURSE: 'loans:disburse',
  LOANS_CLOSE: 'loans:close',
  LOANS_NOC: 'loans:noc',
  REPAYMENTS_READ: 'repayments:read',
  REPAYMENTS_WRITE: 'repayments:write',
  REPAYMENTS_UPDATE: 'repayments:update',
  REPAYMENTS_DELETE: 'repayments:delete',
  REPORTS_READ: 'reports:read',
  HOLIDAYS_READ: 'holidays:read',
  HOLIDAYS_WRITE: 'holidays:write',
  USERS_MANAGE: 'users:manage',
  ROLES_MANAGE: 'roles:manage',
  DOCUMENTS_UPLOAD: 'documents:upload',
})

export const ALL_PERMISSIONS = Object.values(P)

export const EMPLOYEE_DEFAULT_PERMISSIONS = [
  P.DASHBOARD_READ,
  P.LOAN_QUEUE_READ,
  P.LOAN_QUEUE_WRITE,
  P.MEMBERSHIPS_READ,
  P.MEMBERSHIPS_REVIEW,
  P.LOAN_APPLICATIONS_READ,
  P.LOAN_APPLICATIONS_WRITE,
  P.LOANS_READ,
  P.REPAYMENTS_READ,
  P.REPAYMENTS_WRITE,
  P.REPORTS_READ,
  P.HOLIDAYS_READ,
  P.DOCUMENTS_UPLOAD,
]
